name: MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Compile
        working-directory: build
        run: cmake --build . -j 4

      - name: Run
        run: ./build/example
